# Generated by Django 3.1.1 on 2020-09-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iconar2ns',
            options={'verbose_name': 'Icon', 'verbose_name_plural': 'Icons'},
        ),
        migrations.AlterField(
            model_name='iconar2ns',
            name='icon_creation_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
