# Generated by Django 3.1.1 on 2020-09-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200916_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconar2ns',
            name='icon_creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
